name: crop_monitor_app
description: AI-powered crop monitoring mobile application

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI Components
  cupertino_icons: ^1.0.6
  
  # Image handling
  image_picker: ^1.0.7
  
  # HTTP requests (for future API integration)
  http: ^1.2.1
  
  # Local storage
  shared_preferences: ^2.2.2
  
  # Date formatting
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  # Add custom fonts or images here if needed
  # assets:
  #   - assets/images/